package com.mardomsara.emojicon.emoji;

/**
 * Created by Hamid on 5/8/2016.
 */
public class Activities {

    public static final Emojicon[] DATA = new Emojicon[]{
            Emojicon.fromCodePoint2(0x26bd),
            Emojicon.fromCodePoint2(0x1f3c0),
            Emojicon.fromCodePoint2(0x1f3c8),
            Emojicon.fromCodePoint2(0x26be),
            Emojicon.fromCodePoint2(0x1f3be),
            Emojicon.fromCodePoint2(0x1f3d0),
            Emojicon.fromCodePoint2(0x1f3c9),
            Emojicon.fromCodePoint2(0x1f3b1),
            Emojicon.fromCodePoint2(0x26f3),
            Emojicon.fromCodePoint2(0x1f3cc),
            Emojicon.fromCodePoint2(0x1f3d3),
            Emojicon.fromCodePoint2(0x1f3f8),
            Emojicon.fromCodePoint2(0x1f3d2),
            Emojicon.fromCodePoint2(0x1f3d1),
            Emojicon.fromCodePoint2(0x1f3cf),
            Emojicon.fromCodePoint2(0x1f3bf),
            Emojicon.fromCodePoint2(0x26f7),
            Emojicon.fromCodePoint2(0x1f3c2),
            Emojicon.fromCodePoint2(0x26f8),
            Emojicon.fromCodePoint2(0x1f3f9),
            Emojicon.fromCodePoint2(0x1f3a3),
            Emojicon.fromCodePoint2(0x1f6a3),
            Emojicon.fromCodePoint2(0x1f3ca),
            Emojicon.fromCodePoint2(0x1f3c4),
            Emojicon.fromCodePoint2(0x1f6c0),
            Emojicon.fromCodePoint2(0x26f9),
            Emojicon.fromCodePoint2(0x1f3cb),
            Emojicon.fromCodePoint2(0x1f6b4),
            Emojicon.fromCodePoint2(0x1f6b5),
            Emojicon.fromCodePoint2(0x1f3c7),
            Emojicon.fromCodePoint2(0x1f574),
            Emojicon.fromCodePoint2(0x1f3c6),
            Emojicon.fromCodePoint2(0x1f3bd),
            Emojicon.fromCodePoint2(0x1f3c5),
            Emojicon.fromCodePoint2(0x1f396),
            Emojicon.fromCodePoint2(0x1f397),
            Emojicon.fromCodePoint2(0x1f3f5),
            Emojicon.fromCodePoint2(0x1f3ab),
            Emojicon.fromCodePoint2(0x1f39f),
            Emojicon.fromCodePoint2(0x1f3ad),
            Emojicon.fromCodePoint2(0x1f3a8),
            Emojicon.fromCodePoint2(0x1f3aa),
            Emojicon.fromCodePoint2(0x1f3a4),
            Emojicon.fromCodePoint2(0x1f3a7),
            Emojicon.fromCodePoint2(0x1f3bc),
            Emojicon.fromCodePoint2(0x1f3b9),
            Emojicon.fromCodePoint2(0x1f3b7),
            Emojicon.fromCodePoint2(0x1f3ba),
            Emojicon.fromCodePoint2(0x1f3b8),
            Emojicon.fromCodePoint2(0x1f3bb),
            Emojicon.fromCodePoint2(0x1f3ac),
            Emojicon.fromCodePoint2(0x1f3ae),
            Emojicon.fromCodePoint2(0x1f47e),
            Emojicon.fromCodePoint2(0x1f3af),
            Emojicon.fromCodePoint2(0x1f3b2),
            Emojicon.fromCodePoint2(0x1f3b0),
            Emojicon.fromCodePoint2(0x1f3b3),
    };

}
